export const ROUND_BETTING_DURATION_SECONDS = Number(process.env.ROUND_BETTING_DURATION_SECONDS ?? 10);
export const ROUND_CRASHED_DURATION_SECONDS = Number(process.env.ROUND_CRASHED_DURATION_SECONDS ?? 10);
export const CURVE_GROWTH_FACTOR = Number(process.env.CURVE_GROWTH_FACTOR ?? 0.23);
export const MAX_CRASH_POINT = Number(process.env.MAX_CRASH_POINT ?? 1000);

export const ROUND_BETTING_DURATION_MS = ROUND_BETTING_DURATION_SECONDS * 1000;
export const ROUND_CRASHED_DURATION_MS = ROUND_CRASHED_DURATION_SECONDS * 1000;
