export type { AuthenticatedUser } from "./application/authenticated-user.interface";
export type { AuthConfig } from "./infrastructure/auth-config";
export { buildAuthConfig } from "./infrastructure/auth-config";
export { JwtStrategy } from "./infrastructure/jwt.strategy";
export { CurrentUser } from "./presentation/current-user.decorator";
export { JwtAuthGuard } from "./presentation/jwt-auth.guard";
export { SocketJwtAuthService } from "./presentation/socket-jwt-auth.service";
export { WsJwtGuard } from "./presentation/ws-jwt.guard";
export { AuthController } from "./presentation/auth.controller";
export { AuthModule } from "./auth.module";
export type { AuthModuleOptions } from "./auth.module-options";
