export const WALLET_REPOSITORY = Symbol("WALLET_REPOSITORY");
export const WALLET_TRANSACTION_REPOSITORY = Symbol("WALLET_TRANSACTION_REPOSITORY");
export const UNIT_OF_WORK = Symbol("UNIT_OF_WORK");
