_format_version: "3.0"

services:
  - name: games-service
    url: http://games:4001
    routes:
      - name: games-routes
        paths:
          - /games
        strip_path: true
      - name: auth-routes
        paths:
          - /auth
        strip_path: false

  - name: wallets-service
    url: http://wallets:4002
    routes:
      - name: wallets-routes
        paths:
          - /wallets
        strip_path: true
